#!/bin/sh
#| merge-from-trunk                                   -*- Scheme -*-
exec csi -s "$0" "$@"
|#


; usage: merge-from-trunk [--dry-run] [--diff[=REVS]] [--commit] [--repourl=URL] [--verbose]


(load-relative "build.scm")

(define *repourl* "https://galinha.ucpel.tche.br/svn/chicken-eggs")
(define *dry-run* #f)
(define *diff* #f)
(define *commit* #f)

(simple-args)

(run (svn 
      ,(if *diff* 
	   `("diff" ,(if (string? *diff*) (conc "-r" *diff*) ""))
	   "merge")
      ,(if *dry-run* "--dry-run" "")
      ,(conc *repourl* "/chicken/branches/release")
      ,(conc *repourl* "/chicken/trunk")
      ,(if (not *diff*) "." "") ) )

(when *commit*
  (run (svn ci)) )

(exit)
