.\" dummy line
.TH CHICKEN-SETUP 1 "25 Jan 2004"

.SH NAME

chicken-setup - program to simplify building and installation of extension libraries for the
.I CHICKEN
Scheme system.

.SH SYNOPSIS

.B chicken-setup
[
.I option
]
[
.I extension
]

.SH DESCRIPTION

.I chicken\-setup
is a program that compiles and installs a prepackaged extension
library. Extension libraries are either plain Scheme files with the
.B \.scm
file-extension or gzipped tar files with the file-extension
.B \.egg
Single Scheme files are compiled into a dynamically loadable file
and installed in the extension repository. More complex installation
procedures can be performed by packaging an extension in an
.B \.egg
archive, that in addition to the source files contains a Scheme 
script of the same name as the library, but with the 
.B \.setup
file-extension. After extracting the files the setup script will
be loaded and executed. 
If no extension name is given on the command-line, then any
existing 
.B \.setup
scripts in the current directory are processed.
.I chicken\-setup
is a full Scheme interpreter with the same functionality as
.I csi
but with a number of additional procedures and macros to
simplify the building and installation of extension libraries.
See the 
.B Chicken
manual for more information.

.SH OPTIONS

.TP
.B \-check
Downloads the repository-index and lists locally installed extensions for which a newer
release is available for download.

.TP 
.BI \-csc\-option option
Passes 
.B option
as an extra argument to invocations of the compiler-driver (
.I csc
). This works only if 
.I csc
is invoked as 
.I (run\ (csc\ ...))

.TP
.BI \-destdir\ pathname
Specifies alternative installation prefix by setting the
.B installation-prefix
parameter.

.TP
.B \-docindex
Displays the path to the index-page of any installed extension-documentation. If the index page
does not exist, it is created.

.TP
.B \-dont\-ask
Do not ask the user before trying to download required extensions.

.TP
.BI \-eval\ expression
Evaluates the given expression(s).

.TP
.B \-fetch
Only download, don't extract, build or install.

.TP
.B \-fetch\-tree
Downloads and prints the repository catalog to stdout.

.TP
.B \-help
Show usage information and exit.

.TP
.BI \-host\ hostname:port
Specifies alternative host for downloading extensions. 
.B port
may be omitted and defaults to 80.

.TP
.B \-keep
Keep temporary files and directories.

.TP
.B \-list
List all installed extensions and exit, or show extension-information of extensions given on the
command-line (following this option).

.TP
.BI \-local\ path
Fetch extension sources from local filesystem at
.B path
instead of downloading egg from egg server.

.TP
.B \-no\-install
Do not install generated binaries and/or support files. Any invocations of
.I install\-program
,
.I install\-extension
or
.I install\-script
will be be no-ops.

.TP
.B \-program\-path
Display the path where executables are installed.

.TP
.BI \-program\-path\ directory
Sets the location where executables are installed.

.TP
.BI \-proxy\ hostname:port
Connect to server via proxy.
.B port
may be omitted and defaults to 80.

.TP
.B \-repository
Displays the name of the extension repository.

.TP
.BI \-repository\ directory
Sets the location of the extension repository for all subsequent operations.
The default repository path is the installation library directory (usually 
.I \/usr\/local\/lib\/chicken
, or (if set) the directory given in the environment variable 
.I CHICKEN\_REPOSITORY

.TP
.BI \-revision\ revision
Specifies the subversion revision that you want to check out (only useful in
combination with the
.B \-svn
option).

.TP
.BI \-run\ filename
Load and execute given file.

.TP
.BI \-script\ filename
Executes the given Scheme source file with all remaining arguments and exit.

.TP
.BI \-svn\ url
Fetch extension sources from Subversion (http://subversion.tigris.org) repository,
instead of downloading egg from egg server.

.TP
.BI \-tree\ filename
Uses the repository catalog stored in
.B filename
instead of downloading it.

.TP
.B \-uninstall
Removes all following extensions from repository.

.TP
.B \-verbose
Display additional information (mainly for debugging).

.TP
.B \-version
Display version and exit.

.TP
.B \-\-
Ignore all further arguments.

.SH ENVIRONMENT\ VARIABLES

.TP
.B CHICKEN_PREFIX
An alternative installation prefix, where the Scheme-to-C translator 
and any support files and libraries are located. Defaults to the installation
time prefix given when configuring the system.

.TP
.B CHICKEN_REPOSITORY
The path where extension libraries are installed. Defaults to the package-library
path selected during configuration (usually
.B $prefix/lib/chicken/<binary\-version>
)

.TP
.B CHICKEN_SETUP_OPTIONS
A string with default options that should be passed to every invocation of
.B chicken\-setup
.

.SH BUGS
Submit bug reports by e-mail to
.I felix@call-with-current-continuation.org

.SH AUTHOR
.I chicken\-setup
was written by Felix L. Winkelmann (felix@call-with-current-continuation.org).

.SH SEE ALSO
.BR chicken(1)
.BR chicken-config(1)
.BR csc(1)
