.\" dummy line
.TH CHICKEN-SETUP 1 "28 Feb 2008"

.SH NAME

chicken-setup - program to simplify building and installation of extension libraries for the
.I CHICKEN
Scheme system.

.SH SYNOPSIS

.B chicken-setup
[
.I option
]
[
.I extension
]

.SH DESCRIPTION

.I chicken\-setup
is a program that compiles and installs a prepackaged extension
library. Extension libraries are either plain Scheme files with the
.B \.scm
file-extension or gzipped tar files with the file-extension
.B \.egg
Single Scheme files are compiled into a dynamically loadable file
and installed in the extension repository. More complex installation
procedures can be performed by packaging an extension in an
.B \.egg
archive, that in addition to the source files contains a Scheme 
script of the same name as the library, but with the 
.B \.setup
file-extension. After extracting the files the setup script will
be loaded and executed. 
If no extension name is given on the command-line, then any
existing 
.B \.setup
scripts in the current directory are processed.
.I chicken\-setup
is a full Scheme interpreter with the same functionality as
.I csi
but with a number of additional procedures and macros to
simplify the building and installation of extension libraries.
See the 
.B Chicken
manual for more information.

.SH OPTIONS

.TP
.B \-h,\ \-help      
Shows a summary of options and exits.

.TP
.B \-V,\ \-version
Shows the version of 
.I chicken-setup
and exits.

.TP
.B \-release
Shows release number of CHICKEN and exits.

.TP
.BI \-R,\ \-repository \ [PATH]         
If 
.B PATH
is not given, prints the location of the extension repository.
If
.B PATH
is given, specifies the location for the extension repository 
The default repository path is the installation library directory (usually 
.I /usr/local/lib/chicken
, or (if set) the directory given in the environment variable 
.I CHICKEN\_REPOSITORY

.TP
.B \-u,\ \-uninstall
Removes the given extension from the repository.

.TP
.BI \-H,\ \-host \ HOSTNAME[:PORT]
Specifies alternative host for downloading extensions. 
.B PORT
may be omitted and defaults to 80.

.TP
.BI \-p,\ \-proxy \ HOSTNAME[:PORT]
Connects to server via proxy.
.B PORT
may be omitted and defaults to 80.

.TP
.B \-l,\ \-list
Lists all installed extensions and exits, or show extension-information
of extensions given on the command-line (following this option).

.TP
.BI \-r,\ \-run \ FILENAME
Loads and executes given file.

.TP
.BI \-P,\ \-program\-path \ [PATH]
If
.B PATH
is not given, prints the location where executable files will be installed.
If
.B PATH
is given, specifies the location for installing executable files.

.TP
.BI  \-s,\ \-script \ FILENAME           
Executes the given script with remaining arguments and exits.

.TP
.B \-f,\ \-fetch
Only download, don't extract, build or install.

.TP
.B \-v,\ \-verbose
Displays additional information (mainly for debugging).

.TP
.B \-k,\ \-keep
Keeps intermediate files after building and installing.

.TP 
.BI \-c,\ \-csc\-option \ option
Passes 
.B option
as an extra argument to invocations of the compiler-driver (
.I csc
). This works only if 
.I csc
is invoked as 
.I (run\ (csc\ ...))

.TP
.B \-d,\ \-dont\-ask
Does not ask the user before trying to download required extensions.

.TP
.BI \-n,\ \-no\-install
Does not install generated binaries and support files after building.
Any invocations of
.I install\-program
,
.I install\-extension
,
.I install\-script
or
.I copy\-file
will be no-ops.

.TP
.B \-i,\ \-docindex
Displays the path to the index-page of any installed
extension-documentation. If the index page does not exist, it is
created.

.TP
.BI \-e,\ \-eval \ EXPRESSION
Evaluates the given expression(s).

.TP
.BI \-t,\ \-test 
If the 
.B .egg
extension archive contains a directory named
.B tests
and this directory includes a file named
.B run\.scm
then this file is executed (with 
.B tests
being the current working directory).

.TP
.B \-host\-extension
Compiles any extensions in "host" mode.

.TP
.BI \-ls \ EXTENSION
Lists the installed files for the given extension.

.TP
.B \-fetch\-tree
Downloads and prints the repository catalog to standard output.

.TP
.BI \-create\-tree \ PATH
Creates repository catalog from SVN checkout.

.TP
.BI \-tree \ FILENAME
Uses the repository catalog stored in
.B FILENAME
instead of downloading it.


.TP
.BI \-svn \ URL
Fetches extension sources from an SVN repository instead of
downloading egg from egg server.

.TP
.BI \-local \ PATH
Fetches extension sources from the local filesystem at
.B PATH
instead of downloading egg from egg server.

.TP
.BI \-destdir \ PATH
Specifies alternative installation prefix. This affects executable
files, examples, and files installed with the
.I copy-file
procedure.

.TP
.BI \-revision \ REVISION
Specifies the SVN revision that to check out (only useful in
combination with the
.B \-svn
option).

.TP
.BI \-build\-prefix \ PATH
Specifies the location where 
.I chicken-setup
will create build directories. The default location is the value
of environment variable 
.I CHICKEN_TMPDIR
,
.I TMPDIR
or
.I /tmp/chicken-{MAJOR-VERSION}-build-{USER}
if none of those variables are found in the environment. If 
.I /tmp
does not exist or is not writeable, then the build directory is
.I {HOME}/tmp/chicken-{MAJOR-VERSION}-build-{USER}
.


.TP
.BI \-download\-dir \ PATH
Specifies the location where chicken-setup will save downloaded files
The default is 
.I {BUILD-PREFIX}/downloads)


.TP
.B \-\-
Ignores all further arguments.

.SH ENVIRONMENT\ VARIABLES

.TP
.B CHICKEN_PREFIX
An alternative installation prefix, where the Scheme-to-C translator 
and any support files and libraries are located. Defaults to the installation
time prefix given when configuring the system.

.TP
.B CHICKEN_REPOSITORY
The path where extension libraries are installed. Defaults to the package-library
path selected during configuration (usually
.B $prefix/lib/chicken/<binary\-version>
)

.TP
.B CHICKEN_SETUP_OPTIONS
A string with default options that should be passed to every invocation of
.B chicken\-setup
.

.TP
.B CHICKEN_TMPDIR
The location where egg files will be unpacked and extensions compiled.

.SH DOCUMENTATION

More information can be found in the
.I Chicken\ User's\ Manual

.SH BUGS
Submit bug reports by e-mail to
.I chicken-janitors@nongnu.org
, preferrably using the
.B chicken\-bug
tool.

.SH AUTHORS
Felix L. Winkelmann and the Chicken Team

.SH SEE ALSO
.BR chicken(1)
.BR csc(1)
.BR chicken-bug(1)
