.\" dummy line
.TH CHICKEN-BUG 1 "19 Sep 2001"

.SH NAME

chicken-bug - generates a bug report from user input.

.SH SYNOPSIS

.B chicken-bug
[
.I filename
|
.I -help ...
]

.SH DESCRIPTION

.I chicken-bug
generates a bug report file that collects user-input, optional
files and system information obtained from the installed CHICKEN
executables and libraries.

.SH BUGS
Submit bug reports by e-mail to
.I felix@call-with-current-continuation.org

.SH AUTHOR
.I chicken-bug
was written by Felix L. Winkelmann (felix@call-with-current-continuation.org).

.SH SEE ALSO
.BR chicken(1)
