-.\" dummy line
.TH CSI 1 "20 May 2008"

.SH NAME

The
.I Chicken
Scheme interpreter

.SH SYNOPSIS

.B csi
[
.I pathname
|
.I option ...
]

.SH DESCRIPTION

.I csi
is an interpreter for the programming language
.I Scheme
supporting most of the features as described in the
.I Revised^5 Report on
.I the Algorithmic Language Scheme
\.
.I csi
is implemented as a program compiled with the
.B chicken
compiler.

.SH OPTIONS

.TP
.B \-\-
Ignore everything on the command-line following this marker. Runtime options
.B \-\:...
are still recognized.

.TP
.B \-i\ \-case\-insensitive
Enables the reader to read symbols case-insensitive. The default is to read case-sensitive (in violation of R5RS).
This option registers the 
.B case\-insensitive
feature identifier.

.TP
.B \-b\ \-batch
Quit the interpreter after processing all command line options.

.TP
.BI \-e\ \-eval \ expressions
Evaluate
.I expressions
\.

.TP
.BI \-p\ \-print \ expressions
Evaluate 
.I expressions
and print result(s)
\.

.TP
.BI \-P\ \-pretty-print \ expressions
Evaluate 
.I expressions
and pretty-print result(s)
\.

.BI \-D\ \-feature \ symbol
Registers
.I symbol
to be a valid feature identifier for
.B cond\-expand

.TP
.B \-h\ \-help
Write a summary of the available command line options to standard ouput and exit.

.TP
.BI \-I\ \-include\-path \ pathname
Specifies an alternative search-path for files included via the
.B include
special form. This option may be given multiple times. If the environment variable
.B CHICKEN_INCLUDE_PATH
is set, it should contain a list of alternative include
pathnames separated by
.B \; .

.TP
.BI \-k\ \-keyword\-style style
Enables alternative keyword syntax, where style may be either
.B prefix
(as in Common Lisp), 
.B suffix
(as in DSSSL) or
.B none
Any other value is ignored. The default is \texttt{suffix}.

.TP
.B \-n\ \-no\-init
Do not load the initialization-file
.I ~/\.csirc 
\.
If this option is not given and the file
.I ~/\.csirc
exists, then it is loaded before the read-eval-print loop commences. 

.TP
.B \-w\ \-no\-warnings
Disables any warnings that might be issued by the reader or evaluated code.

.TP
.B \-q\ \-quiet
Do not print a startup message.

.TP
.BI \-s\ \-script\  pathname
This is equivalent to
.B \-batch\ \-quiet
.I pathname
, but also ignores all arguments after the argument following
.B \-script

.TP
.BI \-sx\ pathname
Similar to
.B \-script
but invokes prints each expression before it is evaluated,

.TP
.BI \-ss\ pathname
Similar to
.B \-script
but invokes the procedure
.B main
after loading the file specified by
.B pathname
with a single argument (the list of command line arguments) returning any result as status code.

.TP
.BI \-R\ \-require\-extension\  name
Require extension for evaluated code.

.TP 
.B \-v\ \-version
Write the banner with version information to standard output and exit.

.SH ENVIRONMENT\ VARIABLES

.TP
.B CHICKEN_INCLUDE_PATH
Contains one or more pathnames where the interpreter should also look for include-files, separated by 
.B \;
characters.

.TP
.B CHICKEN_PREFIX
Is used as a prefix directory for support files, include-files and libraries.

.TP
.B CSI_OPTIONS
When set to a string of command-line options, then the options are passed implicitly
to every direct or indirect invocation of
.I csi
.br
Note that runtime options of the form
.B \-\:\.\.\.
can not be passed using this method.

.SH DOCUMENTATION

More information can be found in the
.I Chicken\ User's\ Manual

.SH BUGS
Submit bug reports by e-mail to
.I chicken-janitors@nongnu.org
, preferrably using the
.B chicken\-bug
tool.

.SH AUTHOR
Felix Winkelmann and the Chicken Team

.SH SEE ALSO
.BR chicken(1)
.BR chicken-bug(1)
