.\" dummy line
.TH CSI 1 "10 May 2001"

.SH NAME

The
.I Chicken
Scheme interpreter

.SH SYNOPSIS

.B csi
[
.I pathname
|
.I option ...
]

.SH DESCRIPTION

.I csi
is an interpreter for the programming language
.I Scheme
supporting most of the features as described in the
.I Revised^5 Report on
.I the Algorithmic Language Scheme
\.
.I csi
is implemented as a program compiled with the
.B chicken
compiler.

.SH OPTIONS

.TP
.B \-\-
Ignore everything on the command-line following this marker. Runtime options
.B \-\:...
are still recognized.

.TP
.B \-i\ \-case\-insensitive
Enables the reader to read symbols case-insensitive. The default is to read case-sensitive (in violation of R5RS).
This option registers the 
.B case\-insensitive
feature identifier.

.TP
.B \-b\ \-batch
Quit the interpreter after processing all command line options.

.TP
.BI \-e\ \-eval \ expressions
Evaluate
.I expressions
\.

.BI \-D\ \-feature \ symbol
Registers
.I symbol
to be a valid feature identifier for
.B cond\-expand

.TP
.B \-h\ \-help
Write a summary of the available command line options to standard ouput and exit.

.TP
.BI \-I\ \-include\-path \ pathname
Specifies an alternative search-path for files included via the
.B include
special form. This option may be given multiple times. If the environment variable
.B CHICKEN_INCLUDE_PATH
is set, it should contain a list of alternative include
pathnames separated by
.B \; .
The environment variable 
.B CHICKEN_HOME
is also considered as a search path.

.TP
.BI \-k\ \-keyword\-style style
Enables alternative keyword syntax, where style may be either
.B prefix
(as in Common Lisp), 
.B suffix
(as in DSSSL) or
.B none
Any other value is ignored. The default is \texttt{suffix}.

.TP
.B \-n\ \-no\-init
Do not load the initialization-file
.I ~/\.csirc 
\.
If this option is not given and the file
.I ~/\.csirc
exists, then it is loaded before the read-eval-print loop commences. 

.TP
.B \-w\ \-no\-warnings
Disables any warnings that might be issued by the reader or evaluated code.

.TP
.B \-q\ \-quiet
Do not print a startup message.

.TP
.BI \-s\ \-script\  pathname
This is equivalent to
.B \-batch\ \-quiet
.I pathname
, but also ignores all arguments after the argument following
.B \-script

.TP
.BI \-ss\ pathname
Similar to
.B \-script
but invokes the procedure
.B main
after loading the file specified by
.B pathname
with a single argument (the list of command line arguments) returning any result as status code.

.TP
.BI \-R\ \-require\-extension\  name
Require extension for evaluated code.

.TP 
.B \-v\ \-version
Write the banner with version information to standard output and exit.

.SH ENVIRONMENT\ VARIABLES

.TP
.B CHICKEN_INCLUDE_PATH
Contains one or more pathnames where the interpreter should also look for include-files, separated by 
.B \;
characters.

.TP
.B CHICKEN_HOME
Should contain the pathname of a directory where interpreter
support-files can be found. This path is also added to the list of
pathnames where include-filesd are searched.

.TP
.B CSI_OPTIONS
When set to a string of command-line options, then the options are passed implicitly
to every direct or indirect invocation of
.I csi
.br
Note that runtime options of the form
.B \-\:\.\.\.
can not be passed using this method.

.SH DOCUMENTATION

More information can be found in the
.I Chicken\ Manual
which is provided in HTML format as
.B manual\.html
in the distribution.

.SH BUGS
Submit bug reports by e-mail to
.I felix@call-with-current-continuation.org

.SH AUTHOR
.I csi
was implemented by Felix Winkelmann (felix@call-with-current-continuation.org).

.SH SEE ALSO
.BR extend-csi(1)
.BR chicken(1)
.BR chicken-config(1)
