(require-extension utils)
(define-syntax test
  (syntax-rules ()
    ((_ x) `(printf "~s\t=> ~s~%" ',x ,x))))
(test (pathname-directory "/"))
(test (pathname-directory "/abc"))
(test (pathname-directory "abc/"))
(test (pathname-directory "abc/def"))
(test (pathname-directory "abc/def.ghi"))
(test (pathname-directory "abc/.def.ghi"))
(test (pathname-directory "abc/.ghi"))
(test (pathname-directory "/abc/"))
(test (pathname-directory "/abc/def"))
(test (pathname-directory "/abc/def.ghi"))
(test (pathname-directory "/abc/.def.ghi"))
(test (pathname-directory "/abc/.ghi"))
(test (pathname-directory "q/abc/"))
(test (pathname-directory "q/abc/def"))
(test (pathname-directory "q/abc/def.ghi"))
(test (pathname-directory "q/abc/.def.ghi"))
(test (pathname-directory "q/abc/.ghi"))
