(use files)

(assert (equal? "/" (pathname-directory "/")))
(assert (equal? "/" (pathname-directory "/abc")))
(assert (equal? "abc" (pathname-directory "abc/")))
(assert (equal? "abc" (pathname-directory "abc/def")))
(assert (equal? "abc" (pathname-directory "abc/def.ghi")))
(assert (equal? "abc" (pathname-directory "abc/.def.ghi")))
(assert (equal? "abc" (pathname-directory "abc/.ghi")))
(assert (equal? "/abc" (pathname-directory "/abc/")))
(assert (equal? "/abc" (pathname-directory "/abc/def")))
(assert (equal? "/abc" (pathname-directory "/abc/def.ghi")))
(assert (equal? "/abc" (pathname-directory "/abc/.def.ghi")))
(assert (equal? "/abc" (pathname-directory "/abc/.ghi")))
(assert (equal? "q/abc" (pathname-directory "q/abc/")))
(assert (equal? "q/abc" (pathname-directory "q/abc/def")))
(assert (equal? "q/abc" (pathname-directory "q/abc/def.ghi")))
(assert (equal? "q/abc" (pathname-directory "q/abc/.def.ghi")))
(assert (equal? "q/abc" (pathname-directory "q/abc/.ghi")))
